# Remote Embedded Diana Mock PACS
# For use w Resin.io
# Merck, Summer 2018

# resin docker-compose is 2.1 max
version: '2.1'

services:

  dicom:
    build: orthanc
    ports:
      - "2424:4242"
      - "2408:8042"
    privileged: true
    environment:
      # Don not use Resin's init system on a non-Resin base
      INITSYSTEM: "on"

  diana:
    build: diana
    privileged: true
    environment:
      INITSYSTEM: "on"
    volumes_from:
      - dicom